dofile(os.getenv("HOME") .. "/.config/nvim/me/packer.lua")
dofile(os.getenv("HOME") .. "/.config/nvim/me/keymaps.lua")
dofile(os.getenv("HOME") .. "/.config/nvim/me/settings.lua")
dofile(os.getenv("HOME") .. "/.config/nvim/me/specific.lua")
dofile(os.getenv("HOME") .. "/.config/nvim/me/qmk.lua")
dofile(os.getenv("HOME") .. "/.config/nvim/me/python.lua")
